- name: Create Azure VM
  hosts: localhost
  connection: local
  vars:
    resource_group: deploy
    vnet: network
    nic_name: node-1-nic
  tasks:

  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: "{{ resource_group }"
      name: "{{ vnet }}"
      address_prefixes: "10.0.0.0/16"
  - name: Add subnet
    azure_rm_subnet:
      resource_group: myResourceGroup
      name: mySubnet
      address_prefix: "10.0.1.0/24"
      virtual_network: myVnet
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: "{{ resource_group }"
      allocation_method: Dynamic
      name: Node-1-ip
    register: x 
  - name: Public IP of VM
    debug:
      msg: "The public IP is {{ output_ip_address.state.ip_address }}."
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: myResourceGroup
      name: myNetworkSecurityGroup
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
  - name: Create virtual network interface card
    azure_rm_networkinterface:
      resource_group: myResourceGroup
      name: myNIC
      virtual_network: myVnet
      subnet: mySubnet
      public_ip_name: myPublicIP
      security_group: myNetworkSecurityGroup

  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: "{{ resource_group }"
      name: node-1
      vm_size: Standard_B2ms
      admin_username: azureuser
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/azureuser/.ssh/authorized_keys
          key_data: "<key_data>"
      network_interfaces: "{{ nic_name }}"
      image:
        offer: Ubuntu
        publisher: OpenLogic
        sku: '7.5'
        version: latest