name: Continous Intergation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      # Copying the code from the repos to the runner machine
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Installing Node.js on he runner machine
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 10.x
          cache: 'npm'

      # Installing the dependecies in the node_modules folder
      - name: Install Node Modules
        run: npm install

      # Compile and start the applciation
      - name: Build
        run: npm run build --prod

      # Uploading the production build artifacts
      - name: Upload Artications
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: dist/
          if-no-files-found: error