name: Continous Intergation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_Artifact: "build"  # The name of the artifact holding the production build code
  TEST_Artifact: "test"
  CONTAINER_IMG: "image"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      # Copying the code from the repos to the runner machine
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Installing Node.js on he runner machine
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 10.x
          cache: 'npm'

      # Installing the dependecies in the node_modules folder
      - name: Install Node Modules
        run: npm install

      # Compile and start the applciation
      - name: Build
        run: npm run build --prod

      # Moving the Dockerfile to the arficats folder as it will be needed in the containerization job
      - name: Moving Dockerfile
        run: cp Dockerfile dist/

      # Uploading the production build artifacts
      - name: Upload Artications
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.BUILD_Artifact }}
          path: dist/
          if-no-files-found: error


  containerize:

    runs-on: ubuntu-latest
    
    # Specifying the dependency of this (containerize) job on the build job
    needs: build

    steps:
      # Downloading the production build artifacts
      - name: Download application
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.BUILD_Artifact }}

      # Compiling the Dockerfile to a docker image
      - name: Builing Docker Image
        run: docker build . --file Dockerfile --tag app-img:latest

      - run: docker images
